name: habitpal
services:
  local-database:
    image: "postgres:16.4"
    environment:
      POSTGRES_DB: habitpal
      POSTGRES_USER: habitpal
      POSTGRES_PASSWORD: habitpal
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data/
  test-database:
    image: "postgres:16.4"
    environment:
      POSTGRES_DB: habitpal
      POSTGRES_USER: habitpal
      POSTGRES_PASSWORD: habitpal
    ports:
      - "5433:5432"
volumes:
  pg-volume: { }
